-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."product_images" add column "product_image_size" bigint
--  null;
